# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master # 代码提交的时候触发构建部署
  schedule:
    - cron: "0 1 * * *"
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Python Poetry Action
      # You may pin to the exact commit or the version.
      # uses: abatilo/actions-poetry@8284d202bc272a8d0597e26e1c0b4a0d0c73db93
      uses: abatilo/actions-poetry@v2.1.0
      with:
        # The version of poetry to install
        poetry-version: 1.1.7 # default is 1.1.2
    - name: setup-chromedriver
      # You may pin to the exact commit or the version.
      # uses: nanasess/setup-chromedriver@835cae695490330a7e390033b2b5bd67e6f8055e
      uses: nanasess/setup-chromedriver@v1.0.1    
    - name: poetry install
      run: |
        poetry install
    - name: poetry run
      run: |
        poetry run python job.py -a ${{ secrets.COOKIES }} -b ${{ secrets.DING_ACCESS_TOKEN }} -c ${{ secrets.DING_SECRET }}
