# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
#     - name: Poetry Install
#       # You may pin to the exact commit or the version.
#       # uses: knowsuchagency/poetry-install@7ed80d49910319d3e14ac262a5c81f681de48de0
#       uses: knowsuchagency/poetry-install@v2
#       with:
#         # Have poetry create a virtualenv for the project on installation.
#         create-virtualenv: true # optional, default is false
    - name: Poetry setup
      # You may pin to the exact commit or the version.
      # uses: ClementWalter/poetry-action@845abd0cfcc6671c045a2f9df189360bb73e64c4
      uses: ClementWalter/poetry-action@v1
      with:
        # 
        os: ubuntu-latest
        # 
        python-version: 3.9
    - name: setup-chromedriver
      # You may pin to the exact commit or the version.
      # uses: nanasess/setup-chromedriver@835cae695490330a7e390033b2b5bd67e6f8055e
      uses: nanasess/setup-chromedriver@v1.0.1    
    - name: poetry install
      run: poetry install
    - name: Test with pytest
      run: |
        pytest
